### ISSUE TITLE
Plugin toujours d'actualité ?

### ISSUE THREAD

**Issue by Lopinosaurus** [BebeDlaStreat/CiteDesElements#1]
Salut, je voulais savoir si ton plugin était toujours d'actualité ou si le projet avait été abandonné,
Merci d'avance !

**Comment by Benoit-V** [comment]
Bonjour, non
J'ai mis ce code en ligne juste pour mettre du contenu sur github, j'avais commencé à le dev car j'étais dans un projet qui me l'a demandé mais celui-ci s'est vite arrêté donc le code source présent ici est incomplet
Je ne pense pas reprendre un jour ce plugin car je suis occupé pas d'autres chose etc

**Comment by Lopinosaurus** [comment]
Pas de problème, bonne chance dans tes futurs projets et merci pour ta réponse rapide !
